### ISSUE TITLE
Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by RichaBanerjee** [ankit0313/Leetcode-Problems#44]
Hello there! I would like to solve the "Intersection of Two Linked Lists" problem available on LeetCode. Can you please assign it to me?

**Comment by ankit0313** [comment]
Hey I have assigned you the issue you may work on it. Thanks!

**Comment by RichaBanerjee** [comment]
> Hey I have assigned you the issue you may work on it. Thanks!

Thanks!! I am working on it!

**Comment by RichaBanerjee** [comment]
@ankit0313 can you please add the hactoberfest accepted labels??

**Comment by ankit0313** [comment]
@RichaBanerjee the repository already has all the tags so it will automatically be considered for the Hacktoberfest 2023. This repo is operational from last year so no issues with that label.

**Comment by janhavibagret** [comment]
Can you please assign me this issue? I would like to work on it.
